// Generated by CoffeeScript 1.6.2
var assert, async, e, jy, path, pluginDir, populateWithHttp, root, toType;

pluginDir = __dirname + '/../';

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

assert = require('chai').assert;

async = require('async');

path = require('path');

try {
  jy = require('jellyjs');
} catch (_error) {
  e = _error;
  root = __dirname + '/../../../../';
  jy = require("" + root + "/index.js");
}

populateWithHttp = function(params, cb) {
  var jelly;

  jelly = new jy.Jelly();
  return async.waterfall([
    function(cb) {
      var httpServerPlugin;

      httpServerPlugin = path.dirname(require.resolve('jellyjs-plugin-httpserver'));
      return jelly.getPluginDirectoryList().readPluginFromPath(httpServerPlugin, 'httpserver', cb);
    }, function(dt, cb) {
      return dt.getPluginInterface().oncall({}, {
        pluginParameters: {
          httpserver: {
            port: 9876
          }
        }
      }, function(err) {
        return cb();
      });
    }, function(cb) {
      return jelly.getPluginDirectoryList().readPluginFromPath(pluginDir, 'routing', function(err, dt) {
        return cb(err, dt);
      });
    }, function(dt, cb) {
      return dt.getPluginInterface().load(function(err) {
        return cb(err, dt);
      });
    }, function(dt, cb) {
      return dt.getPluginInterface().oncall({}, params, function(err) {
        return cb(err);
      });
    }
  ], cb);
};

describe('#Plugin::routing', function() {
  it('Should load the plugin', function(cb) {
    var jelly;

    jelly = new jy.Jelly();
    return jelly.getPluginDirectoryList().readPluginFromPath(pluginDir, 'routing', function(err, dt) {
      return cb(err);
    });
  });
  it('Should transform everything into templates', function(cb) {
    var jelly;

    jelly = new jy.Jelly();
    jelly.setRootDirectory("" + __dirname + "/demo");
    return async.series([
      function(cb) {
        return jelly.readJellyConfigurationFile(function(err) {
          return cb(err, null);
        });
      }, function(cb) {
        return jelly.readAllGeneralConfigurationFiles(function(err) {
          return cb(err, null);
        });
      }, function(cb) {
        return jelly.getPluginDirectoryList().readPluginFromPath(pluginDir, 'routing', function(err, dt) {
          return cb(err);
        });
      }, function(cb) {
        var httpServerPlugin;

        httpServerPlugin = path.dirname(require.resolve('jellyjs-plugin-httpserver'));
        return jelly.getPluginDirectoryList().readPluginFromPath(httpServerPlugin, 'httpserver', cb);
      }, function(cb) {
        var httpServerPlugin;

        httpServerPlugin = path.dirname(require.resolve('jellyjs-plugin-template'));
        return jelly.getPluginDirectoryList().readPluginFromPath(httpServerPlugin, 'template', cb);
      }, function(cb) {
        return jelly.applyPluginsSpecified(true, function(err) {
          return cb(err);
        });
      }, function(cb) {
        var content, file;

        try {
          file = jelly.getChildByIdRec('module1-file1.tpl');
          content = file.getCurrentContent();
          assert.equal(content.extension, '__template');
          assert.equal(toType(content.content), 'function');
          assert.equal(content.content(), 'TPL TEST');
          return cb();
        } catch (_error) {
          e = _error;
          return cb(e);
        }
      }
    ], function(err) {
      return cb(err);
    });
  });
  it('Should return an error when no httpserver is loaded', function(cb) {
    var jelly;

    jelly = new jy.Jelly();
    return async.waterfall([
      function(cb) {
        return jelly.getPluginDirectoryList().readPluginFromPath(pluginDir, 'routing', function(err, dt) {
          return cb(err, dt);
        });
      }, function(dt, cb) {
        return dt.getPluginInterface().load(function(err) {
          return cb(err, dt);
        });
      }, function(dt, cb) {
        return dt.getPluginInterface().oncall({}, {
          pluginParameters: {}
        }, function(err) {
          try {
            assert.equal(toType(err), 'error');
            return cb();
          } catch (_error) {
            e = _error;
            return cb(e);
          }
        });
      }
    ], cb);
  });
  it('Should raise an error if route.url is undefined', function(cb) {
    return populateWithHttp({
      pluginParameters: {
        routing: {
          routes: [
            {
              method: ["get"],
              oncall: {}
            }
          ]
        }
      }
    }, function(err) {
      try {
        assert.equal(toType(err), 'error');
        return cb();
      } catch (_error) {
        e = _error;
        return cb(e);
      }
    });
  });
  it('Should raise an error if there is an invalid method as an HTTP Verb', function(cb) {
    return populateWithHttp({
      pluginParameters: {
        routing: {
          routes: [
            {
              method: ['invalid'],
              url: '/',
              oncall: {}
            }
          ]
        }
      }
    }, function(err) {
      try {
        assert.equal(toType(err), 'error');
        return cb();
      } catch (_error) {
        e = _error;
        return cb(e);
      }
    });
  });
  return it('Should raise an error if there is an invalid method as oncall', function(cb) {
    return populateWithHttp({
      pluginParameters: {
        routing: {
          routes: [
            {
              method: ['get', 'post'],
              url: '/',
              oncall: {
                type: "invalid"
              }
            }
          ]
        }
      }
    }, function(err) {
      try {
        assert.equal(toType(err), 'error');
        return cb();
      } catch (_error) {
        e = _error;
        return cb(e);
      }
    });
  });
});
